#! /bin/sh
### BEGIN INIT INFO
# Provides:          atd
# Required-Start:    $syslog $time $remote_fs
# Required-Stop:     $syslog $time $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: JupyterHub
# Description:       init script for the JupyterHub server 
#                    
### END INIT INFO
#
# Author:       D.B. Kinghorn <dbkinghorn@...>
#

PATH=/bin:/usr/bin:/sbin:/usr/sbin:/usr/local/bin/:/opt/conda/envs/jupyterhub/bin/
NAME=jupyterhub
DAEMON=/opt/conda/envs/jupyterhub/bin/jupyterhub 
DAEMON_ARGS="-f /opt/conda/envs/jupyterhub/etc/jupyterhub/jupyterhub_config.py"
PIDFILE=/var/run/jupyterhub.pid

test -x $DAEMON || exit 0

. /lib/lsb/init-functions

# Had to use start-stop-daemon since LSB start stop functions failed
do_start()
{
	# Return
	#   0 if daemon has been started
	#   1 if daemon was already running
	#   2 if daemon could not be started
	start-stop-daemon --start --quiet --pidfile $PIDFILE --exec $DAEMON --test > /dev/null \
		|| return 1
	start-stop-daemon --start --background --make-pidfile --quiet --pidfile $PIDFILE --exec $DAEMON -- \
		$DAEMON_ARGS \
		|| return 2
}

case "$1" in
  start)
        log_daemon_msg "Starting $NAME"
        #start_daemon -p $PIDFILE $DAEMON -- $DAEMON_ARGS
        do_start
        log_end_msg $?
    ;;
  stop)
        log_daemon_msg "Stopping $NAME"
        #killproc -p $PIDFILE $DAEMON
        start-stop-daemon --stop --quiet --oknodo --pidfile $PIDFILE
        log_end_msg $?
    ;;
  force-reload|restart)
    $0 stop
    $0 start
    ;;
  status)
    status_of_proc -p $PIDFILE $DAEMON $NAME && exit 0 || exit $?
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|force-reload|status}"
    exit 1
    ;;
esac

exit 0